### ISSUE TITLE
Change God Statues (Full)

### ISSUE THREAD

**Issue by goldstargloww** [felikatze/isat-script-project#114]

**Comment by felikatze** [comment]
yahoo i did it. gonna push w my next pull request yah. this page was so bad. so so bad.

**Comment by goldstargloww** [comment]
i didn't change anything i just opened the issue ':D HJSGDF

**Comment by goldstargloww** [comment]
oh nevermind i got confused because this didn't have any pull requests linked (can you do that in the future btw :goldlurk: i can teach you if needed)
