### ISSUE TITLE
Hallways pages cleanup

### ISSUE THREAD

**Issue by raspberryspider** [felikatze/isat-script-project#181]
by the random Floor 1 header on [/rooms/floor1/hallways1](https://felicitations.neocities.org/rooms/floor1/hallways1), i think there might have once been a plan to put all the hallways on one page? i'm not going to do that tho, that sounds incredibly cluttered (unless someone tells me otherwise).

**Comment by felikatze** [comment]
yeah i initially thought about making them just one page, but decided against it because there IS quite a bit of stuff on there!! Hence i initially made it one, but then split it into the three pages that now exist. I just forgot to remove that heading when I made the change.
