### ISSUE TITLE
Navigation bar font resets to Cascadia when split ("mobnav")

### ISSUE THREAD

**Issue by vixspade** [felikatze/isat-script-project#224]
On mobile or other devices with low width, the top navbar will split itself in two, but the "vcr" class will only apply to the first (top) segment, leaving the other segments in Cascadia Mono.
![image](https://github.com/user-attachments/assets/bd109987-a35f-4a6f-892c-fc5f60097c74)

Seems it can be fixed by adding the "vcr" class to the nav element like this:
`<nav id="mobnav" class="navbar vcr">`

**Comment by felikatze** [comment]
great catch, thank you! turns out this is because the navbar consists of two different uls, but i only put the vcr class on the top one. this'll be fixed with the next pull request in a couple minutes!
