### ISSUE TITLE
"Your Dagger" page missing settings & shaky text in two places

### ISSUE THREAD

**Issue by vixspade** [felikatze/isat-script-project#229]
![image](https://github.com/user-attachments/assets/ad8fd9a3-b8c2-4d50-acfa-bcc4a6184d4d)
these two are supposed to be shaky (source: https://youtu.be/WY-QEtqJ1Co?si=m4UQUL8OmSKHVSHb&t=18)

also the settings button is missing??

**Comment by goldstargloww** [comment]
settings button isn't missing to me, maybe reload? but yes that and the line following should be shaky
![image](https://github.com/user-attachments/assets/557fa2a6-930b-4302-97e8-8642180d93a2)


you can fix that if you like in #228 or something, if not then i'll note that down as a typo to get fixed ^^

**Comment by vixspade** [comment]
![image](https://github.com/user-attachments/assets/68672917-7044-4eef-bdb6-c527908763ca)
oh it's at the top of the page for some reason. but i'll sneak the shake fixes into pr 228 tomorrow :3

**Comment by goldstargloww** [comment]
ah that'd be a css thing, try ctrl + shift + r to reload your css ^^

**Comment by felikatze** [comment]
nice catch! looks like those two lines just didn't get caught in the conversion from i tags to the shake/wave class, probably because i use i tags, so i didn't check whether anyone used em. do you want to add those to your pr, or should i do it?

**Comment by vixspade** [comment]
> nice catch! looks like those two lines just didn't get caught in the conversion from i tags to the shake/wave class, probably because i use i tags, so i didn't check whether anyone used em. do you want to add those to your pr, or should i do it?

you can add them yourself!
