### ISSUE TITLE
settings button is highlighted when you highlight its children buttons

### ISSUE THREAD

**Issue by goldstargloww** [felikatze/isat-script-project#90]
![ID: a gif of the settings button in the corner of the site. when hovered over, the settings button gets lighter, as expected. but when hovering over its children elements, the setting button itself still gets lighter, which shouldn't happen. end ID.](https://github.com/user-attachments/assets/65ad3ac6-718c-472c-83cf-20adec91b565)

small thing but there's probably an easy enough way around it

**Comment by felikatze** [comment]
New settings buttons fixed this!
